// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greeter/greeter.proto

/*
Package go_micro_srv_greeter is a generated protocol buffer package.

It is generated from these files:
	proto/greeter/greeter.proto

It has these top-level messages:
	Request
	Response
	HelloRequest
	Greeting
*/
package go_micro_srv_greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Body *Greeting `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetBody() *Greeting {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Body       *Greeting   `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	Collection []*Greeting `protobuf:"bytes,2,rep,name=collection" json:"collection,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetBody() *Greeting {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetCollection() []*Greeting {
	if m != nil {
		return m.Collection
	}
	return nil
}

type HelloRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Greeting struct {
	// @inject_tag: bson:"_id,omitempty" json:"id"
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty" json:"id"`
	Msg          string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Friendliness int32  `protobuf:"varint,3,opt,name=friendliness" json:"friendliness,omitempty"`
}

func (m *Greeting) Reset()                    { *m = Greeting{} }
func (m *Greeting) String() string            { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()               {}
func (*Greeting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Greeting) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Greeting) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Greeting) GetFriendliness() int32 {
	if m != nil {
		return m.Friendliness
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.greeter.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.greeter.Response")
	proto.RegisterType((*HelloRequest)(nil), "go.micro.srv.greeter.HelloRequest")
	proto.RegisterType((*Greeting)(nil), "go.micro.srv.greeter.Greeting")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Greeter service

type GreeterClient interface {
	GetGreeting(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*Response, error)
	PostGreeting(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetGreetings(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type greeterClient struct {
	c           client.Client
	serviceName string
}

func NewGreeterClient(serviceName string, c client.Client) GreeterClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.greeter"
	}
	return &greeterClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *greeterClient) GetGreeting(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Greeter.GetGreeting", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) PostGreeting(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Greeter.PostGreeting", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetGreetings(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Greeter.GetGreetings", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterHandler interface {
	GetGreeting(context.Context, *HelloRequest, *Response) error
	PostGreeting(context.Context, *Request, *Response) error
	GetGreetings(context.Context, *Request, *Response) error
}

func RegisterGreeterHandler(s server.Server, hdlr GreeterHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Greeter{hdlr}, opts...))
}

type Greeter struct {
	GreeterHandler
}

func (h *Greeter) GetGreeting(ctx context.Context, in *HelloRequest, out *Response) error {
	return h.GreeterHandler.GetGreeting(ctx, in, out)
}

func (h *Greeter) PostGreeting(ctx context.Context, in *Request, out *Response) error {
	return h.GreeterHandler.PostGreeting(ctx, in, out)
}

func (h *Greeter) GetGreetings(ctx context.Context, in *Request, out *Response) error {
	return h.GreeterHandler.GetGreetings(ctx, in, out)
}

func init() { proto.RegisterFile("proto/greeter/greeter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x86, 0xb3, 0x8b, 0x0a, 0x0e, 0x1b, 0xa3, 0xd5, 0x90, 0x15, 0x91, 0x90, 0x9e, 0x88, 0x87,
	0xdd, 0x88, 0x37, 0x13, 0xbd, 0xe2, 0x91, 0xec, 0x1b, 0x00, 0x3b, 0xd6, 0xc6, 0xa5, 0x03, 0x6d,
	0x25, 0x31, 0x46, 0x0f, 0xbe, 0x82, 0x8f, 0xc6, 0x2b, 0xf8, 0x20, 0x86, 0xe2, 0xea, 0x2a, 0x90,
	0x10, 0x3d, 0x4d, 0x33, 0xd3, 0x7f, 0xbe, 0x7f, 0x3a, 0x85, 0x93, 0xb1, 0x26, 0x4b, 0xb1, 0xd0,
	0x88, 0x16, 0x75, 0x1e, 0x23, 0x97, 0x65, 0x47, 0x82, 0xa2, 0x91, 0x1c, 0x6a, 0x8a, 0x8c, 0x9e,
	0x46, 0x9f, 0xb5, 0x7a, 0x43, 0x10, 0x89, 0x0c, 0xe3, 0xfe, 0x58, 0xc6, 0x7d, 0xa5, 0xc8, 0xf6,
	0xad, 0x24, 0x65, 0x16, 0x1a, 0x7e, 0x05, 0xe5, 0x04, 0x27, 0x0f, 0x68, 0x2c, 0xeb, 0xc0, 0xd6,
	0x80, 0xd2, 0xc7, 0xd0, 0x6b, 0x79, 0xed, 0x6a, 0xa7, 0x19, 0xad, 0xea, 0x16, 0x75, 0xe7, 0x51,
	0x2a, 0x91, 0xb8, 0xbb, 0xfc, 0x05, 0x2a, 0x09, 0x9a, 0x31, 0x29, 0x83, 0x7f, 0xd1, 0xb3, 0x6b,
	0x80, 0x21, 0x65, 0x19, 0x0e, 0xe7, 0x9e, 0x42, 0xbf, 0x55, 0xda, 0x40, 0x59, 0x50, 0xf0, 0x26,
	0x04, 0x37, 0x98, 0x65, 0x94, 0xcf, 0xb0, 0x07, 0xbe, 0x4c, 0x9d, 0x83, 0xdd, 0xc4, 0x97, 0x29,
	0xef, 0x41, 0x25, 0xd7, 0xfd, 0xae, 0xb1, 0x7d, 0x28, 0x8d, 0x8c, 0x08, 0x7d, 0x97, 0x98, 0x1f,
	0x19, 0x87, 0xe0, 0x56, 0x4b, 0x54, 0x69, 0x26, 0x15, 0x1a, 0x13, 0x96, 0x5a, 0x5e, 0x7b, 0x3b,
	0xf9, 0x91, 0xeb, 0xcc, 0x7c, 0x28, 0x77, 0x17, 0x96, 0xd8, 0x04, 0xaa, 0x5d, 0xb4, 0x5f, 0x00,
	0xbe, 0xda, 0x78, 0xd1, 0x60, 0x7d, 0xcd, 0x70, 0xf9, 0x23, 0xf2, 0xe6, 0xeb, 0xec, 0xfd, 0xcd,
	0x0f, 0x59, 0xcd, 0xed, 0x6b, 0x7a, 0xbe, 0x58, 0xb1, 0x54, 0xc2, 0xc4, 0x4f, 0x32, 0x7d, 0x66,
	0xf7, 0x10, 0xf4, 0xc8, 0x7c, 0x33, 0x4f, 0xd7, 0xf5, 0xdb, 0x0c, 0xd7, 0x70, 0xb8, 0x1a, 0x3f,
	0x58, 0xc2, 0x5d, 0x7a, 0x67, 0xec, 0x0e, 0x82, 0xc2, 0x7c, 0xe6, 0xbf, 0xb0, 0x63, 0x07, 0x3b,
	0x64, 0xcb, 0xb0, 0xc1, 0x8e, 0xfb, 0x8d, 0x17, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x1b,
	0xc8, 0xcf, 0xe0, 0x02, 0x00, 0x00,
}
