
---

# API

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-service
    spec:
        containers:
        - name: mongo
          image: mongo:latest
          ports:
          - containerPort: 12017
        - name: my-service
          image: eu.gcr.io/tabb-168314/my-service:production
          ports:
          - containerPort: 50051
          - containerPort: 8080
          env:
            - name: DB_HOST
              value: "localhost"
            - name: DB_NAME
              value: greetings
            - name: MICRO_SERVICE_ADDRESS
              value: 0.0.0.0:50051
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - name: my-service-http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-service